### ISSUE TITLE
the LED dssply show semi-colons between 2 numbers (how do I control it)

### ISSUE THREAD

**Issue by donwade** [Seeed-Studio/Seeed_Alphanumeric_Display_HT16K33#2]
If you want to make an alarm clock and would like to use the semi-colons in the middle of the 4 alpha display how is this done.

**Comment by dagwoodland** [comment]
The following code shows an example of how to enable / disable the semi-colon. Where `tube` is the name of your tube variable.


```c++
void displaySemiColon() {
    // Clear the current buffer so that we start with everything off.
    tube.clearBuf();

    // Your code to display the time on the display can go here.

    // True for point on, false for point off. So (true, true) turns both points on, forming a semi-colon.
    tube.setPoint(true, true);

    // Show the updated buffer on the display.
    tube.display();
}
```

Let me know if this helps.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
