### ISSUE TITLE
Library not working on ESP32 boards

### ISSUE THREAD

**Issue by FreddieHong19** [Seeed-Studio/Seeed_Alphanumeric_Display_HT16K33#3]
Trying to run the examples on the ESP32 board. Tested the module working on Arduino boards.
Is this library not supporting ESP32?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Does this problem still exist? If so, can you provide a reproducible environment?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
